import Header from '@/Components/Layout/Header';
import './globals.css';
import { Overpass } from 'next/font/google';
const overpass = Overpass({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={overpass.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
